### ISSUE TITLE
Collapse nodes as you're navigating through the tree

### ISSUE THREAD

**Issue by kapil1garg** [sashaweiss/itree#1]
I would like to be able to collapse nodes that aren't useful to see the tree diagram for. As an example, if you're working with [Meteor](https://www.meteor.com/), the `.meteor` folder contains a lot of build-time files that aren't super useful to see when trying to look at the entire application

**Comment by sashaweiss** [comment]
Love the idea! Will add it to my todo list.

In the meantime, note that if your `.meteor` folder is gitignored, `itree` will ignore it by default - and if not, you can use the `-I` argument to specifically exclude it.

Hope that workaround suffices for the moment!

**Comment by sashaweiss** [comment]
Hey @kapil1garg!

Added this in the 0.2.0 release, which is out now. If you run `brew upgrade itree`, you should then be able to use `f` to dynamically fold/unfold directories!

Closing. Please let me know if you run into bugs!
